spring.application.name=accountBatch
spring.application.propertiespath=C:\\Users\\domin\\workspace\\accountBatch\\target\\classes\\
spring.application.ca_welcome=caterallen_welcome.html
spring.application.ca_login=caterallen_login.html
spring.application.ca_pac=caterallen_pac.html
spring.application.ca_userid_boxid=userNo
spring.application.ca_userid=0060999315
spring.application.ca_pac_no=715162
spring.application.ca_login_button=LOGIN
browser=chrome

